[package]
name = "soloist"
version = "0.1.0"
entrypoint = "soloist.typ"
authors = ["itpyi"]
license = "MIT"
description = "A utility for managing and exporting individual figures from a single file."
repository = "https://github.com/itpyi/typst-plot"
